# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ed8bbdf4fe218a4efc525b54a1796e9ce33a7f242234854edf3880dea32202d815b3eb0e075b9b37177fa5513c03f30baaa8c8d1243649dfdc70a6e81b15c9

test:
  secret_key_base: 91a6d10861b03878938aa2deee12268f699cc2b74cf41bc55680fa1005554a067c399b4d50fb9a74520d7d1aeb8e2530ff21a62d2f951fc7377102a1e7401148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
